module.exports = {
	project: 'VI Frontend Framework 5',
	global: {
		externalResources: {
			'vi-css-helper': ['helper.css', 'print.css'],
			'jquery.debouncedresize': 'js/jquery.debouncedresize.js',
			'@biotope/resource-loader': 'src/resourceLoader.js',
			'jquery': 'dist/jquery.js',
			'jquery-migrate': 'dist/jquery-migrate.js',
			'enquire.js': 'dist/enquire.js',
			'jquery-debouncedwidth': 'js/jquery.debouncedwidth.js',
			'normalize.css': 'normalize.css',
			'@webcomponents/webcomponentsjs': [
				'custom-elements-es5-adapter.js',
				'webcomponents-loader.js',
				'webcomponents-ce.js',
				'webcomponents-hi-ce.js',
				'webcomponents-hi-sd-ce.js',
				'webcomponents-hi-sd.js',
				'webcomponents-hi.js',
				'webcomponents-lite.js',
				'webcomponents-sd-ce.js',
				'webcomponents-sd.js',
			],
		},
	},
	uglify: {
		ignoreList: [
			'resources/js/vendor/custom-elements-es5-adaptor.js',
			'resources/js/vendor/webcomponents-loader.js',
			'resources/js/vendor/webcomponents-ce.js',
			'resources/js/vendor/webcomponents-hi-ce.js',
			'resources/js/vendor/webcomponents-hi-sd-ce.js',
			'resources/js/vendor/webcomponents-hi-sd.js',
			'resources/js/vendor/webcomponents-hi.js',
			'resources/js/vendor/webcomponents-lite.js',
			'resources/js/vendor/webcomponents-sd-ce.js',
			'resources/js/vendor/webcomponents-sd.js',
		],
	},
};
